### ISSUE TITLE
Game Fails to Launch after Renaming "bink2w64_.dll"

### ISSUE THREAD

**Issue by RpgPlayer156** [ReaperAnon/Shadow-Of-War-Mods#3]
Hi,

Thanks for taking the time to make this mod. As per the title, I've followed instructions closely, and the game states bink2w64.dll is missing, so doesn't launch.

Is the mod loader compatible with the latest version or am I doing something stupid?.

Thanks

**Comment by MrMeshok** [comment]
Hi, just tried it on game version 1.21. Everything works with Multi-Equip Skills mod installed
